title: ChuVi's Mundane Adventures
email: johnvinnymarquez@gmail.com
description: >- 
  Vinny Marquez currently works as a Software Development Engineer in Test | 
  Test Automation Engineer at Digi Group while moonlighting as the vocalist | 
  composer for Tito Science & CHVCK.
baseurl: ""
url: "http://vinnymarquez.com" 
github_username:  chuv13
instagram_username:  thedaoofnothing
linkedin_username: vinnymarquez


sass:
  sass_dir: _sass

# Build settings
theme: minima
plugins: ['jekyll-feed','jekyll-paginate', 'jekyll_version_plugin']

favicon:
  source: favicon.svg
  path: /assets

# http://jekyllrb.com/docs/pagination/
paginate: 5
paginate_path: '/blog/page:num/'


permalink: pretty
markdown: kramdown
kramdown:
    auto_ids: false

    # Author information - author info at the bottom of the post
author_name: ChuVi
author_bio: "My name is Vinny, but you can call me ChuVi. SDET by day, vocalist/composer for Tito Science & CHVCK by night."
author_url: "https://vinnymarquez.com"
author_location: "Makati, PH"
author_image: blog/authorimage.jpg

# Footer ad banner
banner_url: "https://vinnymarquez.com/"
banner_image: blog/banner.jpg

# The shortname for your Disqus site to enable comments.
disqus: johnvinnymarquez

# Site navigation - each item must have a title and a url.
navigation:
  - text: Home
    url: /blog
  # - text: Archives
  #   url: /tags/
  - text: About Me
    url: /

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
