# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site title
title: "Part-time ahjussi"

# Site logo
logo: t2vi-logo.png

# A description of your site for social meta tag, search engines, and feed.xml
description: "BlogBox is a bold theme for the Jekyll blogging platform. Available for purchase at ThemeForest.net."

# Tagline below the site title
tagline: "Tito Vi's tales, confessions, and musings."

# The subpath of your site, e.g. /blog, for generating urls
baseurl:

sass:
  sass_dir: css

# The base hostname & protocol of your site for where absolute urls are needed
url: "http://vinnymarquez.com"

# Site navigation - each item must have a title and a url.
navigation:
- text: home
  url: /
- text: About
  url: /about/
# - text: Style Guide
#   url: /style-guide/
# - text: Archives
#   url: /tags/

# The shortname for your Disqus site to enable comments.
disqus: johnvinnymarquez

# Author information - author info at the bottom of the post
author_name: "Tito Vi"
author_bio: "Hi, I'm Tito Vi. Part-time Ahjussi. 3% 'Bae'-material, 97% tito."
author_url: "http://vinnymarquez.com"
author_location: "Makati, Philippines"
author_image: t2vi.jpg

# Footer ad banner
banner_url: "http://vinnymarquez.com"
banner_image: banner.jpg

# Footer newsletter widget - add your form action url for MailChimp signup form here
# mailchimp_url: "//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117"

# Social links in the site footer
twitter_username:
facebook_username:
googleplus_username:
github_username:
codepen_username:
dribbble_username:
medium_username: 
instagram_username:
pinterest_username:
linkedin_username: 

# http://jekyllrb.com/docs/pagination/
paginate: 5
paginate_path: '/blog/page:num/'
plugins: [jekyll-paginate]

permalink: pretty
markdown: kramdown
kramdown:
    auto_ids: false
