# Site settings
title: Metanoia
email: johnvinnymarquez@gmail.com
description: "From Point A to Point B | A blog about my passions, interests and the continous learning process"
baseurl: ""
url: "http://johnvinnymarquez.github.io/"

# Build settings
markdown: kramdown
permalink: pretty

# Theme settings
theme: lumen